- 基本流程
- 特征构造
- 构造"id",重复样本及rank特征,上分背后的原因

In [1]:
import pandas as pd

import numpy as np
import lightgbm as lgb
import xgboost as xgb
import time
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import roc_auc_score as auc
from sklearn.metrics import f1_score
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error as mae
# from sklearn.metrics import mean_absolute_percentage_error as mape
from sklearn.model_selection import StratifiedKFold, KFold

from matplotlib.pyplot import plot, show
from IPython.display import display

from tqdm import tqdm

pd.set_option('max_rows', 500) #显示最多行数，超出该数以省略号表示
pd.set_option('max_columns', 100)

d:\Anaconda3\lib\site-packages\dask\config.py:131: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
d:\Anaconda3\lib\site-packages\dask\dataframe\utils.py:13: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
d:\Anaconda3\lib\site-packages\distributed\config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)

In [2]:
MODEL_TYPE = 'lgb'

LABEL = 'target'

df_train = pd.read_csv('data/train.csv')
df_test = pd.read_csv('data/test.csv')
df_train.shape, df_test.shape

((620356, 13), (206785, 12))

In [3]:
print(df_train.shape, 
      df_test.shape, 
      df_train.drop(columns=['target']).drop_duplicates(subset=[f for f in df_train.columns if f not in ['target', 'uuid', 'common_ts']]).shape,
      df_test.drop_duplicates(subset=[f for f in df_test.columns if f not in ['uuid', 'common_ts']]).shape,
      pd.concat([df_train.drop(columns=['target']), df_test]).drop_duplicates(subset=[f for f in df_test.columns if f not in ['uuid', 'common_ts']]).shape
     )

(620356, 13) (206785, 12) (219956, 12) (98277, 12) (270080, 12)

In [4]:
df_train['udmap'][0], eval(df_train['udmap'][0])

('{"key3":"67804","key2":"650"}', {'key3': '67804', 'key2': '650'})

## 去重

In [5]:
df_train = df_train.drop_duplicates(subset=[f for f in df_train if f not in ['uuid']])
df_train.shape

(617688, 13)

In [6]:
df_train['target'].sum() / df_train['target'].shape[0]

0.1405321132999184

In [7]:
df = pd.concat([df_train, df_test])

In [8]:
a = []
for v in tqdm(df['udmap'].values):
    if v != 'unknown':
        a.extend(list(eval(v).keys()))
keys = sorted(list(set(a)))
keys

100%|██████████████████████████████████████████████████████████████████████| 824473/824473 [00:03<00:00, 248886.08it/s]

['key1', 'key2', 'key3', 'key4', 'key5', 'key6', 'key7', 'key8', 'key9']

In [9]:
keys_df = []
for v in tqdm(df['udmap'].values):
#     print(v)
    if v == 'unknown':
        keys_df.append([-1]*9)
    else:
        v = eval(v)
        this_key = []
        for key in keys:
            if key in v.keys():
                this_key.append(int(v[key]))
            else:
                this_key.append(-1)
        keys_df.append(this_key)
keys_df = pd.DataFrame(keys_df, columns=keys)

100%|██████████████████████████████████████████████████████████████████████| 824473/824473 [00:04<00:00, 181492.61it/s]

In [10]:
keys_df

        key1  key2   key3  key4  key5  key6  key7  key8  key9
0         -1   650  67804    -1    -1    -1    -1    -1    -1
1         -1   484  67804    -1    -1    -1    -1    -1    -1
2         -1    -1     -1    -1    -1    -1    -1    -1    -1
3         -1    -1     -1    -1    -1    -1    -1    -1    -1
4         -1   650  67804    -1    -1    -1    -1    -1    -1
...      ...   ...    ...   ...   ...   ...   ...   ...   ...
824468    -1    -1     -1    -1    -1    -1    -1    -1    -1
824469    -1    -1     -1    -1    -1    -1    -1    -1    -1
824470    -1    -1  87725    -1    -1    -1    -1    -1    -1
824471    -1    -1  65765    -1    -1    -1    -1    -1    -1
824472    -1    -1     -1    -1    -1    -1    -1    -1    -1

[824473 rows x 9 columns]

In [11]:
df = pd.concat([df.reset_index(drop=True), keys_df], axis=1).reset_index(drop=True)

In [12]:
for x in range(1, 9):
    print('-------------', 'x%d'%x)
    display(df['x%d'%x].value_counts())

------------- x1

4    506676
0    164827
1    127239
2     25143
3       588
Name: x1, dtype: int64

------------- x2

0    362161
1    180126
3    166753
2    115433
Name: x2, dtype: int64

------------- x3

41    821158
47       715
15       376
7        348
71       194
34       144
25       124
60       102
70        92
14        89
5         81
27        77
40        76
20        74
35        74
30        69
66        49
11        47
64        40
50        38
55        37
49        34
32        33
38        31
3         30
29        27
56        26
17        25
22        20
36        19
19        17
74        16
21        14
53        13
45        12
18        11
39        11
23        10
0         10
9          9
57         9
2          8
52         7
42         6
4          6
59         6
72         5
58         5
26         5
61         4
28         4
31         3
24         3
67         3
62         3
8          2
12         2
63         2
69         2
33         2
43         1
44         1
73         1
51         1
48         1
1          1
16         1
68         1
10         1
46         1
65         1
13         1
6          1
37         1
Name: x3, dtype: int64

------------- x4

104    114582
85      57349
10      51957
144     51858
71      49497
24      46079
107     44098
17      44097
51      42278
151     33677
115     27290
86      26094
125     25421
143     23638
103     18636
68      17863
106     17140
45      17000
1       16843
111     15624
77      12609
148     10777
57      10199
35       9047
150      8279
38       7937
92       7451
75       4991
8        3549
9        2002
117      1882
129      1749
136       861
20        200
120       194
33        162
28        144
62        131
91         84
79         77
134        73
113        61
42         55
94         53
98         49
59         39
25         38
65         37
146        37
50         33
54         33
149        27
66         25
21         24
119        23
31         21
142        21
110        20
118        19
99         18
139        17
60         17
137        15
16         15
112        14
44         14
19         14
22         13
39         12
126        12
84         11
37         10
105        10
18         10
78         10
23          9
41          9
127         9
88          9
73          8
96          8
34          7
43          6
121         6
81          6
74          6
76          6
29          5
109         5
11          5
56          5
141         5
53          5
147         4
55          4
46          4
0           4
12          4
80          4
116         3
131         3
135         3
83          3
90          3
32          3
102         3
26          3
128         3
5           3
14          3
36          3
132         2
95          2
82          2
61          2
124         2
13          2
93          2
64          2
52          2
63          2
108         2
100         1
15          1
48          1
70          1
27          1
69          1
3           1
140         1
2           1
47          1
67          1
145         1
122         1
72          1
114         1
97          1
40          1
6           1
49          1
101         1
7           1
89          1
30          1
138         1
4           1
133         1
Name: x4, dtype: int64

------------- x5

288    49497
37     47020
305    42278
343    39137
241    32748
250    25480
327    24406
237    22239
183    21897
286    21477
347    18152
133    17140
366    16663
210    15302
217    11321
50     11023
6      10775
108    10471
151    10199
187    10117
130     9037
18      8661
404     8421
386     7855
212     7694
408     7497
279     5472
329     5380
27      5242
49      5146
283     5101
356     4512
367     4445
383     4379
293     4262
171     3995
44      3851
351     3647
340     3636
411     3631
294     3584
22      3547
193     3391
61      3058
228     2875
182     2813
338     2811
98      2714
274     2677
331     2624
249     2603
403     2554
254     2425
319     2386
299     2377
296     2289
163     2274
138     2247
12      2162
157     2147
15      2098
154     2044
0       2020
122     1988
13      1942
40      1933
352     1916
265     1909
209     1907
313     1888
200     1863
107     1857
158     1854
240     1745
101     1745
149     1716
235     1713
267     1711
63      1620
165     1609
60      1608
57      1588
244     1572
52      1558
390     1552
23      1551
39      1521
251     1453
206     1451
46      1449
398     1419
368     1415
290     1405
2       1382
119     1380
300     1376
358     1344
118     1337
230     1336
197     1326
284     1325
273     1303
389     1300
277     1289
365     1258
152     1243
247     1234
79      1230
353     1224
55      1218
405     1215
320     1215
17      1206
3       1200
116     1189
309     1163
233     1156
41      1118
323     1111
346     1106
227     1106
35      1103
168     1102
238     1092
166     1071
321     1071
361     1040
380     1040
147     1033
316     1031
127     1020
385     1014
270     1012
311     1007
310      999
357      985
34       982
162      974
263      974
276      950
208      941
150      939
129      930
153      919
125      905
190      902
236      899
185      891
413      883
161      877
81       874
211      873
144      861
186      849
392      839
287      836
226      829
306      822
43       819
102      816
7        812
295      811
317      810
100      806
80       795
255      792
196      788
10       787
16       777
354      773
289      769
9        753
20       752
220      750
175      741
341      735
203      728
146      728
280      727
229      718
223      703
379      701
266      698
202      696
333      694
213      694
113      690
71       668
412      658
326      658
142      651
92       641
325      639
315      627
378      625
397      624
318      611
382      608
231      605
66       601
282      595
155      592
143      585
51       585
191      582
114      581
339      580
69       575
159      558
402      555
89       552
58       535
297      531
232      529
148      528
84       521
189      515
28       510
78       495
91       493
218      484
139      481
68       478
207      476
75       469
85       461
260      461
372      454
172      442
350      436
121      432
64       429
131      426
225      423
214      419
188      410
342      410
70       407
90       407
345      406
123      400
360      390
304      386
56       384
215      384
111      382
169      380
48       372
302      371
291      369
221      369
348      366
334      363
72       362
388      354
135      353
137      345
312      342
246      341
205      340
19       336
332      334
369      327
234      321
314      317
115      314
269      314
336      314
77       311
32       309
176      303
324      302
410      301
256      300
5        299
42       298
124      291
298      291
337      286
322      286
132      285
376      285
110      285
400      283
396      271
136      266
374      259
65       259
192      257
278      255
36       252
160      246
93       243
88       236
145      234
224      233
54       226
195      225
86       216
194      214
11       210
106      207
178      203
201      200
204      194
62       194
95       189
216      186
349      184
239      172
258      164
335      162
371      160
363      153
24       149
272      148
259      146
82       142
242      140
257      140
399      134
83       132
375      124
355      124
140      123
170      122
74       122
47       116
222      112
96       107
120       99
184       90
308       88
117       84
164       79
401       78
344       77
134       74
177       65
59        59
156       50
395       45
30        44
53        43
328       41
373       41
252       37
307       36
292       35
25        29
406       29
330       29
109       25
33        23
174       23
245       21
112       20
141       20
264       20
126       19
248       18
387       17
14        17
198       15
393       15
103       14
38        13
128       12
253       12
391        9
94         9
394        9
21         9
281        8
4          8
199        7
381        7
97         6
87         6
261        6
243        6
29         6
1          6
8          6
359        5
167        5
268        5
271        5
362        5
262        5
409        4
181        4
301        4
370        4
179        4
104        4
45         3
407        3
384        3
76         3
99         3
219        3
364        2
180        2
275        1
26         1
31         1
73         1
173        1
67         1
303        1
Name: x5, dtype: int64

------------- x6

4    522353
1    301551
3       466
2        78
0        25
Name: x6, dtype: int64

------------- x7

7    246223
6    172977
2    119047
8    102791
9     98622
0     51958
4     21521
3      8474
5      2843
1        17
Name: x7, dtype: int64

------------- x8

1    705426
0    119047
Name: x8, dtype: int64

In [13]:
for x in range(1, 10):
    print('key%d'%x, df[df['key%d'%x]==-1].shape[0] / df.shape[0])
#     df[~df.isna()].shape[0]

key1 0.9183769510948205
key2 0.6007874120802016
key3 0.5455691089944729
key4 0.8680684509983954
key5 0.8680684509983954
key6 0.9926377213080355
key7 0.9988744325162862
key8 0.9988501745963785
key9 0.9975693564252559

## 时间戳转换-交叉

In [14]:
df['tm'] = pd.to_datetime(df['common_ts'],unit='ms')
df['day'] = df['tm'].dt.day
df['hour'] = df['tm'].dt.hour
df['dayofweek'] = df['tm'].dt.dayofweek

df['x5_x7'] = df['x5'].astype(str) + '_' + df['x7'].astype(str)
df['x5_x4'] = df['x5'].astype(str) + '_' + df['x4'].astype(str)
df['x7_x4'] = df['x7'].astype(str) + '_' + df['x4'].astype(str)
# 笛卡尔积

df['hour_x7'] = df['hour'].astype(str) + '_' + df['x7'].astype(str)
df['hour_x7_x5'] = df['hour_x7'] + '_' + df['x5'].astype(str)
df['x_all'] = df['x1'].astype(str) + '_'+ df['x2'].astype(str) + '_' + df['x3'].astype(str) + '_' + df['x4'].astype(str)+ '_' + df['x5'].astype(str)+ '_' + df['x6'].astype(str)+ '_' + df['x7'].astype(str)+ '_' + df['x8'].astype(str)

df['hour_x_all'] = df['hour'].astype(str) + '_' + df['x_all']

for f in ['x5_x7', 'x5_x4', 'x7_x4', 'hour_x7', 'hour_x7_x5', 'x_all', 'hour_x_all',]:
    df[f] = df[f].factorize()[0]

## rank特征(统计)

In [17]:
df = df.reset_index()

In [22]:
df['x_all'].value_counts()

284      3662
2        3533
148      2979
66       2798
121      2629
         ...
14840       1
14841       1
14842       1
11323       1
16786       1
Name: x_all, Length: 16787, dtype: int64

In [31]:
df[df['x_all']==66].sort_values(by='common_ts')[['common_ts', 'target']].dropna()[:100]

            common_ts  target
451925  1688695619410     0.0
393383  1688695619411     0.0
352432  1688695631063     0.0
555284  1688695632182     0.0
330296  1688695632183     0.0
542654  1688695632878     0.0
139030  1688695644375     0.0
165639  1688695649672     0.0
410429  1688695649723     0.0
100463  1688695649723     0.0
156685  1688695656017     0.0
554844  1688695657302     0.0
377408  1688710592593     1.0
367127  1688710596260     1.0
370241  1688711963851     0.0
424093  1688711965783     0.0
232533  1688711967228     0.0
99584   1688711968918     0.0
69859   1688711972362     0.0
165874  1688711972362     0.0
322483  1688711977027     0.0
154916  1688711982323     0.0
296260  1688711991513     0.0
63391   1688711993601     0.0
340038  1688711993667     0.0
108343  1688712000812     0.0
337432  1688712002472     0.0
561214  1688714305959     0.0
85179   1688714458339     1.0
214506  1688714586411     0.0
83816   1688714610726     0.0
205597  1688714610844     0.0
417024  1688714610845     0.0
433364  1688714616921     0.0
78397   1688714723390     0.0
466723  1688714723391     0.0
564014  1688715237525     1.0
385453  1688715359199     1.0
221024  1688715359199     1.0
407102  1688715363234     1.0
111416  1688715366285     1.0
304860  1688715371679     1.0
479585  1688715479088     1.0
376271  1688715490433     1.0
363569  1688715601269     1.0
144112  1688715606825     1.0
321111  1688715606912     1.0
308668  1688718032850     0.0
48463   1688733234805     0.0
617143  1688733249384     0.0
425455  1688733249590     0.0
366419  1688733261948     0.0
240983  1688733281484     0.0
514476  1688736773564     0.0
340159  1688736928414     0.0
590900  1688736934793     0.0
309389  1688738222498     0.0
151812  1688738224556     0.0
43968   1688738226459     0.0
585066  1688738233802     0.0
517497  1688738235126     0.0
572582  1688738241807     0.0
454056  1688738242585     0.0
399786  1688738244761     0.0
201707  1688738253786     0.0
578739  1688739691467     0.0
408725  1688739691896     0.0
65141   1688739692030     0.0
131529  1688739692031     0.0
585247  1688739805865     1.0
84229   1688741825511     0.0
451328  1688741853534     0.0
548320  1688741858969     0.0
586981  1688743437962     0.0
547726  1688743455847     0.0
43472   1688743457789     0.0
297116  1688744217239     0.0
527467  1688745734459     0.0
100213  1688748646336     0.0
209002  1688766951632     0.0
195940  1688767171844     0.0
417743  1688768256731     0.0
281395  1688772622722     0.0
421730  1688772633311     0.0
554883  1688774580598     1.0
415932  1688774668863     1.0
300240  1688774672250     0.0
237104  1688774687383     1.0
266836  1688774688725     1.0
105352  1688774738963     1.0
268431  1688774762596     1.0
168875  1688774782395     1.0
35306   1688774842032     1.0
275035  1688777790279     0.0
116956  1688777790343     0.0
234161  1688777795895     0.0
171960  1688777806142     0.0
406738  1688777809193     0.0
250412  1688777819251     0.0
109099  1688777821431     0.0

In [14]:
df = df.sort_values(by=['common_ts'])
for f in ['eid', 'x4', 'x5', 'x7', 'hour', 'hour_x7_x5', 'hour_x7', 'x5_x7', 'x_all', 'hour_x_all',
         ]:
    df[f+'_sort_ts_rank'] = df.groupby(f)['common_ts'].rank()
df = df.sort_values(by=['index'])

In [15]:
for f in ['eid', 'x4', 'x5', 'x7', 'hour', 'hour_x7_x5', 'hour_x7', 'x5_x7', 'x_all', 'hour_x_all',]:
    df[f+'_ts_std'] = df.groupby([f])['common_ts'].transform('std')
    df[f+'_ts_skew'] = df.groupby([f])['common_ts'].transform('skew')

In [13]:
df_train = df[df[LABEL].notna()].reset_index(drop=True)
df_test = df[df[LABEL].isna()].reset_index(drop=True)

In [23]:
df_train[df_train['x_all']==4].sort_values(by=['common_ts'])['target']

10937     1.0
597336    1.0
147974    1.0
507343    1.0
250845    1.0
264401    1.0
511937    1.0
479811    1.0
402189    1.0
353463    0.0
145992    0.0
447237    0.0
489974    0.0
391110    0.0
31529     0.0
382601    0.0
81433     0.0
399164    0.0
296873    0.0
98166     0.0
402014    0.0
33516     0.0
490211    0.0
4         0.0
100676    0.0
340472    0.0
264973    0.0
Name: target, dtype: float64

In [14]:
feats = [f for f in df_test if f not in [LABEL, 'udmap', 'uuid',  'key4', 'key5', 'key6', 'key7', 'key8', 'key9', 'tm', 'index']]

In [15]:
print(df_train[feats].shape, df_test[feats].shape)
params_lgb = {
    'learning_rate': 0.1,
    'boosting_type': 'gbdt',
    'objective': 'binary',
    'metric': 'auc',
    'num_leaves': 64,
    'verbose': -1,
    'seed': 2222,
    'n_jobs': -1,

    'feature_fraction': 0.8,
    'bagging_fraction': 0.9,
    'bagging_freq': 4,
    # 'min_child_weight': 10,
}

params_xgb = {
    'objective': 'binary:logistic',
    'tree_method': 'gpu_hist',
    'eval_metric': 'auc',
    'eta': 0.1,
    'max_depth': 6,
    'subsample':0.8,
    'colsample_bytree': 0.9,
    'seed': 2222
}

fold_num = 5
seeds = [2222]
oof = np.zeros(len(df_train))
importance = 0
pred_y = pd.DataFrame()

for seed in seeds:
    kf = StratifiedKFold(n_splits=fold_num, shuffle=True, random_state=seed)
    # kf = KFold(n_splits=fold_num, shuffle=True, random_state=seed)
    for fold, (train_idx, val_idx) in enumerate(kf.split(df_train[feats], df_train[LABEL])):
        print('-----------', fold)
        if MODEL_TYPE == 'lgb':
            train = lgb.Dataset(df_train.loc[train_idx, feats],
                                df_train.loc[train_idx, LABEL])
            val = lgb.Dataset(df_train.loc[val_idx, feats],
                              df_train.loc[val_idx, LABEL])
            model = lgb.train(params_lgb, train, valid_sets=[val], num_boost_round=20000, early_stopping_rounds=100, verbose_eval=1000,)
                              # callbacks=[lgb.early_stopping(100), lgb.log_evaluation(1000)])

            oof[val_idx] += model.predict(df_train.loc[val_idx, feats]) / len(seeds)
            pred_y['fold_%d_seed_%d' % (fold, seed)] = model.predict(df_test[feats]) / len(seeds)
            importance += model.feature_importance(importance_type='gain') / fold_num

        elif MODEL_TYPE == 'xgb':
            train = xgb.DMatrix(df_train.loc[train_idx, feats],
                                df_train.loc[train_idx, LABEL])
            val = xgb.DMatrix(df_train.loc[val_idx, feats],
                              df_train.loc[val_idx, LABEL])
            watchlist = [(train, 'train'), (val, 'eval')]
            model = xgb.train(params_xgb, dtrain=train, evals=watchlist, num_boost_round=20000,
                              early_stopping_rounds=100, maximize=True,
                              verbose_eval=1000)

            oof[val_idx] += model.predict(xgb.DMatrix(df_train.loc[val_idx, feats])) / len(seeds)
            pred_y['fold_%d_seed_%d' % (fold, seed)] = model.predict(xgb.DMatrix(df_test[feats]))
            d = model.get_score(importance_type='total_gain')
            d = np.array(list(d.values()))
            importance += np.pad(d, (0, len(feats) - len(d)))

feats_importance = pd.DataFrame()
feats_importance['name'] = feats
feats_importance['importance'] = importance
print(feats_importance.sort_values('importance', ascending=False)[:30])

df_train['oof'] = oof

best_score = 0
best_thre = 0
for thre in np.arange(0.1, 0.5, 0.05):
    score = f1_score(df_train[LABEL], (df_train['oof']>thre).astype(int))
    if score > best_score:
        best_score = score
        best_thre = thre
        print(best_thre, best_score)
print(best_score)

(617688, 13) (206785, 13)
----------- 0

d:\Anaconda3\lib\site-packages\lightgbm\engine.py:181: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
d:\Anaconda3\lib\site-packages\lightgbm\engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "

Training until validation scores don't improve for 100 rounds
[1000]	valid_0's auc: 0.937413
[2000]	valid_0's auc: 0.952089
[3000]	valid_0's auc: 0.958279
[4000]	valid_0's auc: 0.96116
[5000]	valid_0's auc: 0.962616
[6000]	valid_0's auc: 0.963571
[7000]	valid_0's auc: 0.964099
Early stopping, best iteration is:
[7291]	valid_0's auc: 0.964224
----------- 1
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's auc: 0.937977
[2000]	valid_0's auc: 0.951024
[3000]	valid_0's auc: 0.957183
[4000]	valid_0's auc: 0.959751
[5000]	valid_0's auc: 0.9611
Early stopping, best iteration is:
[5418]	valid_0's auc: 0.961689
----------- 2
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's auc: 0.936944
[2000]	valid_0's auc: 0.950787
[3000]	valid_0's auc: 0.95716
[4000]	valid_0's auc: 0.96011
[5000]	valid_0's auc: 0.961481
Early stopping, best iteration is:
[5823]	valid_0's auc: 0.962348
----------- 3
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's auc: 0.936707
[2000]	valid_0's auc: 0.951169
[3000]	valid_0's auc: 0.957637
[4000]	valid_0's auc: 0.960323
[5000]	valid_0's auc: 0.961863
[6000]	valid_0's auc: 0.962709
[7000]	valid_0's auc: 0.963307
Early stopping, best iteration is:
[7028]	valid_0's auc: 0.963331
----------- 4
Training until validation scores don't improve for 100 rounds
[1000]	valid_0's auc: 0.937851
[2000]	valid_0's auc: 0.950962
[3000]	valid_0's auc: 0.957099
[4000]	valid_0's auc: 0.959894
[5000]	valid_0's auc: 0.961505
[6000]	valid_0's auc: 0.962713
Early stopping, best iteration is:
[6895]	valid_0's auc: 0.963262
         name     importance
1   common_ts  423706.443649
6          x5  291061.913829
8          x7  210280.314266
5          x4  187162.294512
0         eid  149951.492179
3          x2  109354.821291
12       key3   96872.425741
2          x1   87014.712065
11       key2   44620.721586
7          x6   32595.851052
9          x8   20280.435109
10       key1   13689.459077
4          x3    2447.461314
0.1 0.6954436239779618
0.15000000000000002 0.737265363534947
0.20000000000000004 0.7606476775304442
0.25000000000000006 0.7740018570102136
0.30000000000000004 0.7810233533309404
0.3500000000000001 0.7846382070816023
0.7846382070816023

In [ ]:
# (617688, 53) (206785, 53)
# ----------- 0
# d:\Anaconda3\lib\site-packages\lightgbm\engine.py:181: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
#   _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
# d:\Anaconda3\lib\site-packages\lightgbm\engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
#   _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
# Training until validation scores don't improve for 100 rounds
# [1000]	valid_0's auc: 0.975696
# [2000]	valid_0's auc: 0.982098
# [3000]	valid_0's auc: 0.983663
# [4000]	valid_0's auc: 0.984294
# Early stopping, best iteration is:
# [4542]	valid_0's auc: 0.984432
# ----------- 1
# Training until validation scores don't improve for 100 rounds
# [1000]	valid_0's auc: 0.974368
# [2000]	valid_0's auc: 0.980596
# [3000]	valid_0's auc: 0.982185
# Early stopping, best iteration is:
# [3289]	valid_0's auc: 0.982456
# ----------- 2
# Training until validation scores don't improve for 100 rounds
# [1000]	valid_0's auc: 0.97453
# [2000]	valid_0's auc: 0.980494
# [3000]	valid_0's auc: 0.98226
# [4000]	valid_0's auc: 0.98298
# Early stopping, best iteration is:
# [4037]	valid_0's auc: 0.983001
# ----------- 3
# Training until validation scores don't improve for 100 rounds
# [1000]	valid_0's auc: 0.975677
# [2000]	valid_0's auc: 0.981781
# [3000]	valid_0's auc: 0.983286
# Early stopping, best iteration is:
# [3774]	valid_0's auc: 0.983653
# ----------- 4
# Training until validation scores don't improve for 100 rounds
# [1000]	valid_0's auc: 0.975064
# [2000]	valid_0's auc: 0.981505
# [3000]	valid_0's auc: 0.983234
# [4000]	valid_0's auc: 0.983782
# Early stopping, best iteration is:
# [3960]	valid_0's auc: 0.9838
#                        name    importance
# 34              eid_ts_skew  93153.911417
# 52       hour_x_all_ts_skew  81273.017014
# 51        hour_x_all_ts_std  75164.677705
# 33               eid_ts_std  73207.213428
# 22               hour_x_all  65931.350918
# 50            x_all_ts_skew  65027.528705
# 49             x_all_ts_std  63886.986879
# 1                 common_ts  62560.596397
# 26          x7_sort_ts_rank  59706.186481
# 24          x4_sort_ts_rank  57060.310923
# 21                    x_all  54196.977088
# 32  hour_x_all_sort_ts_rank  54169.391934
# 27        hour_sort_ts_rank  52930.691247
# 31       x_all_sort_ts_rank  52377.495661
# 29     hour_x7_sort_ts_rank  51379.724489
# 44       hour_x7_x5_ts_skew  50686.233981
# 25          x5_sort_ts_rank  45908.781051
# 20               hour_x7_x5  43695.571866
# 43        hour_x7_x5_ts_std  43529.325864
# 8                        x7  43429.990503
# 30       x5_x7_sort_ts_rank  42704.392993
# 28  hour_x7_x5_sort_ts_rank  39118.217463
# 48            x5_x7_ts_skew  34487.354775
# 40               x7_ts_skew  32173.208515
# 16                    x5_x7  30865.711155
# 47             x5_x7_ts_std  30120.981897
# 41              hour_ts_std  30100.112833
# 37                x5_ts_std  30025.881714
# 18                    x7_x4  29794.721170
# 45           hour_x7_ts_std  29469.130217
# 0.1 0.8156959020426382
# 0.15000000000000002 0.845904952325669
# 0.20000000000000004 0.8621264774952168
# 0.25000000000000006 0.8703134392443107
# 0.30000000000000004 0.8756299674723632
# 0.3500000000000001 0.8781466704664197
# 0.8781466704664197

In [24]:
df_test[LABEL] = pred_y.mean(axis=1).values
df_test[LABEL] = (df_test[LABEL] > thre).astype(int)
df_test[['uuid', LABEL]].to_csv(time.strftime('ans/lgb_%Y%m%d %H%M')+'_%.5f.csv'%best_score, index=False)

In [42]:
ts_df = df_train[df_train['common_ts'].isin(df_test['common_ts'].unique())].groupby('common_ts')['target'].mean().reset_index()
ts_df['target'] = (ts_df['target']>0.4).astype(int)
ts_df = df_train.groupby('common_ts')['target'].mean().reset_index()

In [33]:
ans = pd.read_csv('ans/lgb_20230821 2034_0.87815.csv')
df_test['target_old'] = ans['target']
tmp = df_test[['uuid', 'common_ts', 'target_old']].merge(ts_df, how='left', on='common_ts')
tmp.loc[tmp['target'].isna(), 'target'] = tmp.loc[tmp['target'].isna(), 'target_old'].values
tmp['target'] = tmp['target'].astype(int)
tmp[['uuid', 'target']].to_csv('ans/lgb_20230821 2034_0.87815_post.csv', index=False)

In [ ]:
# 嵌入
# gensim => word2vec